
development:
  adapter: mysql2
  database: final_db
  username: root
  password: password
  pool: 5
  encoding: utf8
  reconnect: true

dev:
  adapter: mysql2
  database: final_db
  username: root
  password: password
  pool: 5
  encoding: utf8
  reconnect: true

staging:
  adapter: mysql2
  database: filnal_staging
  username: root
  password: password
  pool: 5
  encoding: utf8
  reconnect: true

production:
  adapter: mysql2
  database: filnal_prod
  username: root
  password: password
  pool: 5
  encoding: utf8
  reconnect: true